### ISSUE TITLE
Error occured while reading

### ISSUE THREAD

**Issue by sasholy** [devanshbatham/revwhoix#2]
`    
❌ Error occured while reading /home/kali/.config/whoisxml.conf
⚠ Make sure a valid API Key exists at /home/kali/.config/whoisxml.conf
`
I can't create a file: whoisxml.conf

how to fix it?
thx.

**Comment by devanshbatham** [comment]
```
sudo nano /home/kali/.config/whoisxml.conf
```

Paste your API key, and you are should be all set.
